apiVersion: batch/v1
kind: CronJob
metadata:
  name: apache-cronjob
spec:
  schedule: "*/1 * * * *"  # Every 1 minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: apache
            image: apache:latest
          restartPolicy: Never

